name: Bug 报告
title: "[<Agent 组件: 框架|工具|大模型|其他...>] "
description: 提交 CodeAgent 代码相关的问题或故障
labels: [bug]
assignees:
  - LittleYoungFish
  - Moxing04
body:
  - type: markdown
    attributes:
      value: |
        感谢你反馈问题！请确保你所报告的是可复现的 Bug，若仅为使用咨询/功能建议，
        请前往 [讨论区](https://github.com/LittleYoungFish/CodeAgent/discussions) 发帖，而非提交 Bug 报告。

  - type: checkboxes
    id: checks
    attributes:
      label: 前置检查
      description: |
        提交前请确认以下事项，避免重复反馈或无效提问
      options:
        - label: 我已搜索过相关 Issues 和文档，但未找到有效解决方案
          required: true
        - label: 该 Bug 在最新版本中仍未修复
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug 详细描述
      description: 清晰、简洁地描述你遇到的问题，包含「操作行为、实际结果、预期结果」
      placeholder: >
        为帮助我们快速定位问题，请提供以下信息：
            1. 你执行了什么命令/脚本？（粘贴完整命令）
            2. 实际发生了什么异常？（比如报错、功能异常、无响应等）
            3. 你预期的正常结果应该是什么？
            4. 若有报错信息，请粘贴完整的日志输出（请勿只贴截图，复制文本日志）
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: 复现步骤
      description: 提供可稳定复现该 Bug 的操作步骤（越详细越好）
      placeholder: |
        1. 环境准备：安装 XX 依赖、配置 XX 参数
        2. 执行命令：python xxx.py
        3. 触发操作：点击 XX 按钮/输入 XX 内容
        4. 观察到 Bug 出现
    validations:
      required: true

  - type: textarea
    id: env-info
    attributes:
      label: 环境/依赖版本
      description: 请指定使用的 CodeAgent、Python、操作系统及其他关键依赖版本
      placeholder: >
        - Python 版本：例如 3.9.18
        - 操作系统：例如 Windows 11 / Ubuntu 22.04
        - 核心依赖：例如 torch 2.1.0、modelscope 1.9.5
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 补充信息（可选）
      description: 其他有助于定位问题的信息（如截图、日志文件、修改过的代码等）
      placeholder: |
        例如：
        1. 相关截图：（可粘贴图片链接或直接上传）
        2. 自定义配置：修改了 config.yaml 中的 XX 参数
        3. 其他备注：仅在特定场景下复现（如并发请求时）
    validations:
      required: false
